Feature/first
itk-dev-rpa/nedhentning-af-optagelser-fra-miralix pull request #1
Opened 2024-11-01 13:02 UTC by bakspace-itk

2024-11-08 13:02 UTC, ghbm-itk requested changes

2024-11-08 13:02 UTC, ghbm-itk commented on README.md
> +{"case_number": "EMN-2024-123456", "target_queues":["89403330 Opkrævningen P-Gap","89403330 Opkrævningen P-Gap Boliglån tast 2")]}
Are those real phone numbers and case numbers?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/config.py
> +SSK = "Miralix Shared Key"
SSK?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/process.py
> +    case_id = json.loads(orchestrator_connection.process_arguments)["case_number"]
Is it a number or an id? ;)

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/process.py
> +    highest_id = last_download = 0
```suggestion
    max(int(queue_element.reference) for queue_element in queue_elements)
```

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/process.py
> +        last_download = max(highest_id, int(queue_element.reference))
highest_id is always 0, right?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/process.py
> +        print(f"{i+1}/{len(recordings)} - Call ID {call_id} being saved as {filename}")
Should this be a log?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/process.py
> +    oc = OrchestratorConnection("Miralix Nedhentning", conn_string, crypto_key, '{"case_number": "EMN-2024-033020", "target_queues":["89403330 Opkrævningen P-Gap","89403330 Opkrævningen P-Gap Boliglå
Is this data we want in git?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    session.post(apiurl, timeout=config.GO_TIMEOUT)
What is the point of this post request?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    url = apiurl + "/_goapi/Documents/AddToCase"
url join?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    response = session.post(url, data=json.dumps(payload), timeout=config.GO_TIMEOUT)
Should we raise an HTTP error here?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    response = session.post(url, data=json.dumps(payload), timeout=config.GO_TIMEOUT)
Same question for all requests

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +        }
:(

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    # Return the response
This comment smells of AI 😅

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +def journalize_document(apiurl, doc_id, session) -> tuple[str, Session]:
Is it journalized or finalized?

2024-11-08 13:02 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    print("main")
🥳

2024-11-18 11:42 UTC, bakspace-itk commented on README.md
> +{"case_number": "EMN-2024-123456", "target_queues":["89403330 Opkrævningen P-Gap","89403330 Opkrævningen P-Gap Boliglån tast 2")]}
Real phone numbers, fake case number. Fixed.

2024-11-27 12:57 UTC, ghbm-itk approved these changes
There are still some unresolved comments but otherwise it looks good

2024-11-27 12:57 UTC, ghbm-itk commented on robot_framework/get_organized/get_organized_api.py
> +    session.post(apiurl, timeout=config.GO_TIMEOUT)
?

2024-12-02 10:29 UTC, merged